import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

import { PlainLegalLinks } from "@/components/plain-legal-links";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { Button } from "@/components/ui/button";
import { siteConfig } from "@/config/nav";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${siteConfig.name}. Learn about data collection, user rights, and compliance with KSP community guidelines.`,
};

export default function TermsOfServicePage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* First in the DOM on purpose: the plain-HTML copies of both documents,
          reached before the header by a screen reader or a Tab press. */}
      <PlainLegalLinks />
      <SiteHeader />
      <main className="flex-1">
        {/* Hero */}
        <section className="relative overflow-hidden border-b border-border/60">
          <div className="pointer-events-none absolute inset-0 glow-grid opacity-40" />
          <div className="pointer-events-none absolute -top-32 left-1/2 h-[22rem] w-[40rem] -translate-x-1/2 rounded-full bg-primary/8 blur-3xl" />
          <div className="container relative py-16 sm:py-20">
            <div className="mx-auto max-w-3xl">
              <Button
                asChild
                variant="ghost"
                size="sm"
                className="mb-6 -ml-3 text-muted-foreground"
              >
                <Link href="/">
                  <ArrowLeft className="mr-1.5 h-4 w-4" />
                  Back to home
                </Link>
              </Button>
              <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
                Terms of Service
              </h1>
              <p className="mt-3 text-muted-foreground">
                Last updated · <time dateTime="2026-08-24">24 August 2026</time>
              </p>
            </div>
          </div>
        </section>

        {/* Content */}
        <section className="container py-14 sm:py-20">
          <article className="prose-tos mx-auto max-w-3xl space-y-12 text-[15px] leading-relaxed text-muted-foreground">
            {/* 1. Agreement */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                1. Agreement to Terms
              </h2>
              <p>
                By installing, accessing or using any part of {siteConfig.name},
                including the Kerbal Space Program (KSP) add-on, the Discord
                bot, or this website (collectively, the &ldquo;Service&rdquo;),
                you agree to be bound by these Terms of Service
                (&ldquo;Terms&rdquo;). If you do not agree, do not use the
                Service.
              </p>
              <p className="mt-3">
                These Terms are written in accordance with the{" "}
                <a
                  href="https://forum.kerbalspaceprogram.com/topic/154851-add-on-posting-rules-april-13-2021/"
                  target="_blank"
                  rel="noreferrer"
                  className="text-primary underline underline-offset-4 transition-colors hover:text-primary/80"
                >
                  KSP Forum Add-on Posting Rules
                </a>{" "}
                (specifically Rule&nbsp;8 on privacy and data collection) and
                reflect the standards the KSP modding community expects.
              </p>
            </div>

            {/* 2. Definitions */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                2. Definitions
              </h2>
              <ul className="mt-3 list-inside list-disc space-y-1.5 pl-1">
                <li>
                  <strong className="text-foreground">Service:</strong> The Kerbal Space Program (KSP) add-on, the Discord bot, and this website collectively.
                </li>
                <li>
                  <strong className="text-foreground">Integrity checks:</strong> The server verifies that the connecting add-on is a supported version and that requests come from a device bound to the account. A new device is blocked until the account owner approves it from Discord. These checks protect accounts and the shared economy.
                </li>
                <li>
                  <strong className="text-foreground">Device identifier:</strong> A random identifier the add-on generates on first run, carrying no personal or hardware information, used for the device binding above. See the Privacy Policy for details.
                </li>
                <li>
                  <strong className="text-foreground">KSP.log:</strong> The standard diagnostic log file generated by Kerbal Space Program, used to identify software errors and verify game integrity during a report.
                </li>
              </ul>
            </div>

            {/* 3. Age Requirement */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                3. Age Requirement
              </h2>
              <p>
                By using the Service, you represent that you are at least 13
                years of age{" "}
                <strong className="text-foreground">and</strong> at least the
                minimum age of digital consent in your country. Some
                countries set this higher than 13 (for example, up to 16 in
                parts of the European Economic Area), and in that case the
                higher age applies. If you are under the age of majority where you live
                (typically 18), you must have your parent or legal
                guardian&rsquo;s permission to agree to these Terms and to
                use the Service. We do not knowingly collect personal
                information from children under 13.
              </p>
            </div>

            {/* 4. Description of Service */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                4. Description of the Service
              </h2>
              <p>
                {siteConfig.name} is a community-driven project consisting of:
              </p>
              <ul className="mt-3 list-inside list-disc space-y-1.5 pl-1">
                <li>
                  A <strong className="text-foreground">KSP add-on</strong>{" "}
                  (mod) that integrates community features into Kerbal Space
                  Program.
                </li>
                <li>
                  A <strong className="text-foreground">Discord bot</strong>{" "}
                  providing economy, contracts, weekly missions and account
                  linking.
                </li>
                <li>
                  A <strong className="text-foreground">companion website</strong>{" "}
                  hosting documentation, these Terms, and related resources.
                </li>
              </ul>
              <p className="mt-3">
                The KSP add-on and Discord bot are{" "}
                <strong className="text-foreground">
                  100% free and open-source
                </strong>
                , and the hosted Service is{" "}
                <strong className="text-foreground">
                  currently free for all players
                </strong>
                . All source code is publicly available under the{" "}
                <strong className="text-foreground">
                  GNU General Public License v3.0 (GPL-3.0)
                </strong>
                , meaning anyone is free to study, modify and redistribute the
                code in accordance with that licence.
              </p>
              <p className="mt-3">
                Please understand what you are joining:{" "}
                <strong className="text-foreground">
                  {siteConfig.name} is a new project
                </strong>
                . It is not financially stable, it runs on a limited
                infrastructure budget, and its architecture has not yet been
                proven under mass use. We therefore cannot promise that free
                access can be sustained at any scale. If running costs exceed
                what we can absorb, we may have to limit capacity or restrict
                who can use the hosted servers. The mod itself stays free and
                open-source either way. Any material change to how access
                works will be announced through the Discord server and/or
                this website before it takes effect.
              </p>
              <p className="mt-3">
                <strong className="text-foreground">
                  Reservation of rights.
                </strong>{" "}
                We reserve the right, at any time and at our sole discretion,
                to limit, suspend (including permanently) or remove any
                user&apos;s access to the hosted servers; to restrict access
                to an approved whitelist; to modify, suspend or discontinue
                any part of the Service; or to shut the Service down entirely.
                Where reasonably possible, material changes will be announced
                through the Discord server and/or this website in advance.
                Your data-deletion
                rights under the Privacy Policy survive all of these measures.
              </p>
              <p className="mt-3">
                <strong className="text-foreground">
                  Removal of content.
                </strong>{" "}
                We may remove, delist or delete any user-generated content
                uploaded to the Service&rsquo;s database (craft files,
                screenshots, custom flags, marketplace listings, contract text
                and anything else you submit) at any time, with or
                without reason, and without prior notice. A removal is not by
                itself a finding that you did anything wrong: it may follow a
                moderation decision, but it may equally come down to storage,
                running costs, or the Service no longer carrying that kind of
                content. Keep your own copies of anything you care about; the
                Service is not a backup. Removing content does not on its own
                suspend your account or delete the rest of your data, and it
                cannot recall copies already delivered to other players
                (see Section 7).
              </p>
            </div>

            {/* 5. Privacy & Data */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                5. Privacy and Data
              </h2>
              <p>
                Your privacy matters. Our full{" "}
                <Link
                  href="/pp"
                  className="text-primary underline underline-offset-4 transition-colors hover:text-primary/80"
                >
                  Privacy Policy
                </Link>{" "}
                describes in detail what data we collect (Discord account
                link, a random device identifier, IP address, gameplay data,
                website activity and, in the report flows only, your
                KSP.log), why we collect it, who processes it on our
                behalf, and how you can control it. The key points are:
              </p>
              <ul className="mt-3 list-inside list-disc space-y-1.5 pl-1">
                <li>
                  <strong className="text-foreground">No data before consent.</strong>{" "}
                  The add-on collects nothing until you explicitly opt in
                  through the in-game consent window.
                </li>
                <li>
                  <strong className="text-foreground">Opt out any time.</strong>{" "}
                  Toggle data sharing off in the mod toolbar under Settings to
                  stop all collection immediately.
                </li>
                <li>
                  <strong className="text-foreground">Data deletion.</strong>{" "}
                  Use{" "}
                  <code className="rounded bg-card px-1.5 py-0.5 text-xs text-primary">
                    /b deletemydata
                  </code>{" "}
                  in Discord, or email us, to have your personal data permanently
                  removed &mdash; your profile, your account and sign-in, your
                  friend list, your catalogs and your corporation. Records that
                  are also somebody else&apos;s (contracts and auctions you were
                  party to, support tickets, and craft files another player has
                  already bought) are kept; your listings are delisted so nothing
                  further is sold. Section 6 of the{" "}
                  <a
                    className="text-primary underline underline-offset-2"
                    href="/pp"
                  >
                    Privacy Policy
                  </a>{" "}
                  sets this out in full.
                </li>
                <li>
                  <strong className="text-foreground">No third-party sharing.</strong>{" "}
                  We never sell, rent or share your data with third parties
                  for their own use, and we never use it for advertising. The
                  infrastructure runs on Google Firebase, and submissions may
                  be reviewed with Google&apos;s Gemini AI; the service
                  providers acting on our behalf are listed in the Privacy
                  Policy.
                </li>
              </ul>
            </div>

            {/* 6. User Conduct */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                6. User Conduct
              </h2>
              <p>When using the Service, you agree not to:</p>
              <ul className="mt-3 list-inside list-disc space-y-1.5 pl-1">
                <li>
                  Exploit, cheat or tamper with the economy, contract or
                  mission systems.
                </li>
                <li>
                  Reverse-engineer, decompile or otherwise attempt to extract
                  server-side source code or secrets.
                </li>
                <li>
                  Abuse, harass or impersonate other community members.
                </li>
                <li>
                  Embed or share flags, decals or other images that contain
                  personal information (your own or anyone else&rsquo;s)
                  such as real names, faces, addresses, contact
                  details, identity or payment documents, or private
                  conversations.
                </li>
                <li>
                  File false or bad-faith reports against other players,
                  devices or marketplace listings.
                </li>
                <li>
                  Circumvent a suspension, device approval, or any other
                  enforcement or integrity measure.
                </li>
                <li>
                  Interfere with the operation of the Service or its
                  infrastructure.
                </li>
              </ul>
              <p className="mt-3">
                Violations may result in removal or delisting of content, and
                in a{" "}
                <strong className="text-foreground">
                  temporary or permanent suspension
                </strong>{" "}
                from the Service (see also the reservation of rights in
                Section 4). A service suspension blocks access to the online
                features but deletes nothing: your balance, progress,
                contracts and listings are preserved, and your data deletion
                and log-out rights remain available throughout (see the
                Privacy Policy). Moderation within the community Discord
                server itself, including bans from that server, is separate
                and governed by Discord&apos;s own Terms of Service.
              </p>
              <p className="mt-3">
                <strong className="text-foreground">
                  Flags and embedded images.
                </strong>{" "}
                A flag embedded in a craft is delivered into the game of
                everyone who receives that craft, and copies already installed
                cannot be recalled. Crafts found to carry a flag containing
                personal information are therefore removed: the listing is
                delisted, the stored files are deleted, and the craft is
                withdrawn from any transfer or contract still carrying it. This
                applies whether the information is yours or someone
                else&rsquo;s, and is in addition to the measures above.
              </p>
              <p className="mt-3">
                Some reviews and checks (such as contract-submission review)
                are automated. If you believe an automated or moderation
                decision is wrong, you can raise it with the moderation team
                through a ticket or the contact channels in Section 12.
              </p>
            </div>

            {/* 7. Intellectual Property */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                7. Intellectual Property
              </h2>
              <p>
                {siteConfig.name} is a community project. Content you submit
                (craft files, screenshots, custom flags, etc.) remains your
                property; by submitting it you grant us a non-exclusive,
                revocable licence to display and distribute it within the
                Service.
              </p>
              <p className="mt-3">
                Note that some sharing is delivery, not display: a craft sold
                on the marketplace, traded through a contract, or quicksent is
                installed into the recipient&apos;s own game (together with
                anything embedded in it, such as custom flags). Revoking your
                licence or deleting your data stops us from distributing it
                further, but cannot recall copies already delivered to other
                players&apos; machines.
              </p>
              <p className="mt-3">
                <strong className="text-foreground">
                  Promotional use of your crafts.
                </strong>{" "}
                You also grant us a non-exclusive, worldwide, royalty-free
                licence to use the crafts you share through the Service, including
                the craft file itself, the blueprint sheets and thumbnails the
                add-on renders from it, and the screenshots you submit
                alongside it, to promote {siteConfig.name}. In practice
                that means showing your craft in places such as the Discord
                server, this website, the add-on&apos;s release pages and forum
                threads, and posts about the project on social media. We credit
                you by your Discord display name wherever the format allows; we
                do not sell your crafts, licence them on to third parties, or
                use them to advertise anything other than the Service itself.
                This licence is revocable on the same terms as the rest of this
                section: tell us and we will stop using your craft in new
                material, though we cannot always withdraw material that is
                already published or that others have since reposted.
              </p>
              <p className="mt-3">
                &ldquo;Kerbal Space Program&rdquo; and associated branding are
                the property of their respective owners. {siteConfig.name} is
                not affiliated with, endorsed by, or officially connected to
                Squad, Private Division, or Take-Two Interactive.
              </p>
            </div>

            {/* 8. Disclaimers */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                8. Disclaimer of Warranties
              </h2>
              <p>
                The Service is provided{" "}
                <strong className="text-foreground">
                  &ldquo;as-is&rdquo;
                </strong>{" "}
                and{" "}
                <strong className="text-foreground">
                  &ldquo;as-available&rdquo;
                </strong>
                , without warranty of any kind, express or implied. We do not
                guarantee uptime, accuracy, or that the Service will be
                error-free. In particular, the Service is an early-stage
                community project running on limited infrastructure that has
                not been tested under heavy load: outages, degraded
                performance and interruptions are possible at any time, and
                the Service may be restricted or discontinued as described in
                Section 4. Use the Service at your own risk.
              </p>
            </div>

            {/* 9. Limitation of Liability */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                9. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by applicable law, the{" "}
                {siteConfig.name} team shall not be liable for any indirect,
                incidental, special or consequential damages arising from your
                use of the Service, including but not limited to data loss,
                corrupted save files, or service interruptions.
              </p>
            </div>

            {/* 10. Changes */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                10. Changes to These Terms
              </h2>
              <p>
                We may update these Terms from time to time. When we do, we
                will update the &ldquo;Last updated&rdquo; date at the top of
                this page and, for material changes, notify users through the
                Discord server, this website and/or an in-game prompt. For
                material changes the
                add-on also stops transmitting data and asks you to read and
                accept the updated Terms before continuing. Continued use of
                the Service after changes constitutes acceptance.
              </p>
            </div>

            {/* 11. Billing and Access */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                11. Billing and Access
              </h2>
              <p>
                The Service is{" "}
                <strong className="text-foreground">free</strong>. There is
                nothing to bill: access is not sold, no feature is locked
                behind a payment, and we never collect or store payment
                details. Any voluntary support you give us through a
                third-party platform buys nothing here: it grants no access,
                no advantage and no in-game currency. If this ever changes it
                will be announced through the Discord server and/or this
                website before it takes effect, and these Terms will be
                updated.
              </p>
            </div>

            {/* 12. Contact */}
            <div>
              <h2 className="mb-4 text-xl font-semibold text-foreground">
                12. Contact
              </h2>
              <p>
                Questions about these Terms? Reach out to us via email at{" "}
                <a href="mailto:legal@boundlessmissions.com" className="text-primary underline underline-offset-4 transition-colors hover:text-primary/80">
                  legal@boundlessmissions.com
                </a>
                . For account help, bug reports and anything else, email{" "}
                <a href="mailto:support@boundlessmissions.com" className="text-primary underline underline-offset-4 transition-colors hover:text-primary/80">
                  support@boundlessmissions.com
                </a>
                , ask in the {siteConfig.name} Discord server, or open an issue on our{" "}
                <Link
                  href="/github"
                  className="text-primary underline underline-offset-4 transition-colors hover:text-primary/80"
                >
                  GitHub repositories
                </Link>
                .
              </p>
            </div>
          </article>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
