import type { Metadata } from "next";
import Link from "next/link";

import { DocHeader, Section, Callout } from "@/components/docs-ui";
import { DocPager } from "@/components/doc-pager";
import { Card, CardContent } from "@/components/ui/card";
import {
  ScanLine,
  ClipboardCheck,
  Tags,
  ListFilter,
  Puzzle,
} from "lucide-react";

export const metadata: Metadata = {
  title: "AI Integration",
  description:
    "The six places Gemini is called, what it is never used for, how results are cached, and exactly what happens when it is unavailable.",
};

const uses = [
  {
    icon: ScanLine,
    title: "Screenshot analysis",
    body: "Reads a KSP screenshot a member posts and returns the craft, the location and a difficulty rating as structured data, which the reward is then calculated from.",
    fallback: "Disabled. Screenshots are not analysed and no reward is paid.",
  },
  {
    icon: ClipboardCheck,
    title: "Reviewing a submission",
    body: "Given the mission text and the submitted screenshots, judges whether the work matches what was asked for. The in-game path additionally sends the vessel telemetry.",
    fallback: "The submission is auto-accepted rather than blocked.",
  },
  {
    icon: Tags,
    title: "Classifying one contract",
    body: "Turns a mission text into a type (build a craft or fly a vessel), a situation, a target body, and the constraints its wording implies.",
    fallback: "Keyword heuristics produce the same shape of answer.",
  },
  {
    icon: ListFilter,
    title: "Classifying a week of missions",
    body: "The same thing for a whole week's board in one call, rather than twenty.",
    fallback: "Keyword heuristics, per mission.",
  },
  {
    icon: Puzzle,
    title: "Resolving a loosely named part",
    body: "Pins a part a mission text refers to by an informal name onto an actual installed part.",
    fallback: "Keyword heuristics.",
  },
];

export default function AiPage() {
  return (
    <article>
      <DocHeader
        eyebrow="Under the Hood"
        title="AI Integration"
        description="Gemini is used in a handful of narrow places where the alternative is asking a human to read something. It is never used to write the content players read, and every call site has a working fallback."
      />

      <Section title="What it is not used for">
        <p>
          Weekly missions are <strong className="text-foreground">not</strong>{" "}
          generated by a model. They are drawn from a hand written template pool,
          and the descriptions in them are authored. The model&rsquo;s only role
          there is classifying a mission that already exists.
        </p>
        <p>
          Nothing a player reads is model-written except one field: the reason
          attached to a submission review. Contract text is written by the issuer
          who is paying for it, mission text is written by hand, and the
          interface strings are translated rather than generated.
        </p>
      </Section>

      <Section title="Where it is called">
        <div className="space-y-4">
          {uses.map((use) => (
            <Card key={use.title}>
              <CardContent className="flex gap-4 p-5">
                <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg border border-border bg-accent/40 text-primary">
                  <use.icon className="h-5 w-5" />
                </span>
                <div>
                  <h3 className="font-semibold text-foreground">{use.title}</h3>
                  <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
                    {use.body}
                  </p>
                  <p className="mt-2 text-xs text-muted-foreground">
                    <span className="font-medium text-foreground">
                      Without it:
                    </span>{" "}
                    {use.fallback}
                  </p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
        <p>
          Submission review is called from two places, the Discord path and the
          in-game path, which is why the count of call sites is six rather than
          five.
        </p>
      </Section>

      <Section title="One gate in front of all of them">
        <p>
          Every call site asks the same helper for a client, and that helper
          returns nothing in two cases: no API key is configured, or the monthly
          AI budget is spent. So a blown budget degrades exactly like a missing
          key, and there is no separate code path to get wrong.
        </p>
        <Callout variant="info" title="Failing towards the player">
          <p>
            Notice which way each fallback leans. A submission that cannot be
            reviewed is accepted rather than refused, because a model being
            unavailable is not the contractor&rsquo;s fault. A screenshot that
            cannot be analysed pays nothing rather than paying a guess.
          </p>
        </Callout>
      </Section>

      <Section title="Caching">
        <p>
          Classification results are stored in Firestore, so a set of missions is
          classified once and reused rather than re-sent every time somebody
          opens the board. That keeps both cost and latency predictable, and it
          is what makes the weekly board free to look at.
        </p>
        <p>
          Screenshot analysis is separately rate limited per player, three calls
          a minute, because each one is a paid request drawn from a budget
          everybody shares.
        </p>
      </Section>

      <Section title="Language">
        <p>
          Anything the model reads is language-agnostic: a mission written in any
          language is classified the same way. Two things are not. The keyword
          fallbacks match English and Turkish tables, and screenshot analysis
          pins its output fields to English on purpose so the same screenshot
          produces the same record whoever posted it.
        </p>
        <p>
          The Turkish tables are not dead code. The crew and profession heuristic
          runs on every classification to fill in bounds the model left unset,
          not only when the model is unavailable.
        </p>
        <p>
          For the budget mechanism behind the gate, see{" "}
          <Link
            href="/docs/how-does-it-work/architecture"
            className="text-primary hover:underline"
          >
            Architecture
          </Link>
          .
        </p>
      </Section>

      <DocPager
        prev={{ title: "Architecture", href: "/docs/how-does-it-work/architecture" }}
        next={{ title: "Privacy & Your Data", href: "/docs/how-does-it-work/privacy" }}
      />
    </article>
  );
}
